### ISSUE TITLE
Improve the appearance of the block code

### ISSUE THREAD

**Issue by taikii** [taikii/whiteplain#11]
* Change characters more smaller
* Chromastyle will changes to someone from Monokai

**Comment by josephting** [comment]
I thought this is just some settings in config.toml?
Is there any changes that have to be made in terms of theme?

Other than reducing the font-size slightly, of course.

**Comment by taikii** [comment]
@josephting Since I already changed the font on cf9f4673b452eff8b0b28327131824a9ce49ff9e, I would like to close this Issue. Thank you!
