### ISSUE TITLE
The first line of code misaligned

### ISSUE THREAD

**Issue by fu-sen** [taikii/whiteplain#15]
Please take a closer look at this:
![2018-10-20 19 46 52](https://user-images.githubusercontent.com/5434159/47254785-92a65e80-d4a1-11e8-98ef-dbb04b15f83b.jpg)

Only the first line of code is misaligned.
Of course this happens even at the demo site.

It is caused by dual application because it uses the same CSS for pre and code.
I am avoiding the problem with this custom.css:

> code {
>   padding-left: 0;
>   padding-right: 0;
> }

**Comment by taikii** [comment]
@fu-sen Thank you for your report!
I fixed this problem as 194147f.
