### ISSUE TITLE
Images missing max-width property

### ISSUE THREAD

**Issue by paskal** [taikii/whiteplain#2]
Hello!

I've stumbled upon the very same issue as the https://github.com/dim0627/hugo_theme_beg/issues/19, only part of the image visible on the screenshot where whole should be:
![image](https://user-images.githubusercontent.com/712534/37676690-a436d096-2c89-11e8-9715-4bec536307a7.png)

Source code:

    ![Shinken simple distributed architecture](https://shinken.readthedocs.io/en/latest/_images/shinken-architecture.png)

**Comment by taikii** [comment]
@paskal Thank you for your report!
I fixed this problem. Could you check it?

**Comment by paskal** [comment]
It works like a charm! Thanks a lot!

**Comment by paskal** [comment]
![image_artefact](https://user-images.githubusercontent.com/712534/37847880-68b32446-2ee3-11e8-90f5-1571346cdf2a.jpg)
There is still room for improvement. TOC doesn't work well with images.

**Comment by paskal** [comment]
I'm not sure github sent notifications to mentioned authors, so posting double there: theme highlight blog post is out, this very theme is in it, additional info on https://github.com/paskal/terrty/issues/1.

**Comment by taikii** [comment]
> There is still room for improvement. TOC doesn't work well with images.

I feel that the problem is difficult...
I will look for the solution if time accept.

Thank you for picking this theme up in your blog!
I am surprised your evaluation, That is much higher than I imagined!!
