### ISSUE TITLE
Issue with link to static assets

### ISSUE THREAD

**Issue by cbluth** [taikii/whiteplain#20]
Please see the attached screenshot.

I would like to serve the site from a sub-directory, but the css and js assets are getting a 404 because the links arent relative.
How do i fix that?

![image](https://user-images.githubusercontent.com/6709636/53307321-7f642f00-3897-11e9-855c-f1009e313587.png)

**Comment by taikii** [comment]
@cbluth Are you writing sub-directory in the `baseURL` of `config.toml`?

e.g.
```toml
baseURL = "http://localhost:9998/public/"
```

**Comment by cbluth** [comment]
@taikii 
i will check it out, thanks
