### ISSUE TITLE
Please remove social media tracking

### ISSUE THREAD

**Issue by onedrawingperday** [taikii/whiteplain#24]
Hello I am one of the maintainers of [Hugo Themes](https://themes.gohugo.io/).

As described in https://github.com/gohugoio/hugoThemes/issues/564 your theme features share buttons from social media networks that track users in `\whiteplain\layouts\partials\share.html`

I kindly request that you remove the tracking code. 

I understand that your theme has been approved with the tracking code but currently the guidelines for maintaining a theme on the Hugo Themes list are about to change and the requirement to not include tracking in Hugo Themes will be included in the new guidelines.

I suggest that you re-write to the above partial as described in this resource: https://sharingbuttons.io

If you have any questions then please do not hesitate to ask.

Looking forward to your reply.

cc: @digitalcraftsman

**Comment by taikii** [comment]
Hello @onedrawingperday 

Thank you for your great advice.
I tried to fix it, but is it OK? #25

**Comment by onedrawingperday** [comment]
Hello @taikii 

Thanks for the fixes. When you can please merge https://github.com/taikii/whiteplain/pull/25

I consider this issue fixed so I'm closing it.
