### ISSUE TITLE
Enabling navigation sidebar

### ISSUE THREAD

**Issue by gchapidze** [taikii/whiteplain#33]
Hey there! How did you enable navigation sidebar in a ```markdown-syntax.md``` example?

**Comment by taikii** [comment]
@gchapidze 
Are you talking about TOC?
Automatically generated for articles over 400 words.
You can force generation by writing `toc: true` in FrontMatter.
Conversely, by writing `toc: false`, TOC will not be generated even if the length is 400 words or more.
In the case of CJK, the number of words cannot be counted correctly.

**Comment by gchapidze** [comment]
Yes, it did the trick. Thanks!
