### ISSUE TITLE
Error: Deprecated DisqusShortname Prevents Site from Building in Whiteplain Hugo Theme

### ISSUE THREAD

**Issue by robotAstray** [taikii/whiteplain#35]
**Description:**

While using the Whiteplain Hugo theme, I encountered an error related to the deprecated `DisqusShortname`. This error prevents the Hugo site from building correctly.

**Steps to Reproduce:**

1. Create a Hugo site using the Whiteplain theme.
2. Run the following command:

    ```bash
    hugo server --buildDraft
    ```

3. The site fails to build, and the following error message is seen.

**Error:**

    ```
    ERROR deprecated: .Site.DisqusShortname was deprecated in Hugo v0.120.0 and will be removed in Hugo 0.134.0. Use .Site.Config.Services.Disqus.Shortname instead.
    Built in 12 ms
    Error: error building site: logged 1 error(s)
    ```

**Expected Behavior:**

The site should build successfully without any errors. The theme should use the updated property `.Site.Config.Services.Disqus.Shortname` instead of the deprecated `.Site.DisqusShortname`.

**Environment:**

- Hugo Version: 0.134.0
- OS: macOS

**Proposed Solution:**

Replace the deprecated `.Site.DisqusShortname` with `.Site.Config.Services.Disqus.Shortname` in the `layouts/_default/single.html` file.

**Additional Context:**

I have opened a PR to address this issue: #34

**Comment by robotAstray** [comment]
@taikii let me know your thoughts on this. Thank you.

**Comment by taikii** [comment]
@robotAstray 
Thank you for your PR. Sorry for the late reply.
I would like to merge your PR, but I don't want to change the text color. Could you please revert style.css file change?

**Comment by robotAstray** [comment]
@taikii yes of course! I changed it for my work and forgot to change it back. I will fix that now.

**Comment by taikii** [comment]
Thank you for your great job! I have merged it.
